---
title: "Visualizing Epiviz Charts with epivizrChart"
author: "Brian Gottfried"
output:
   BiocStyle::html_document
---

```{r setup, eval=TRUE, include=FALSE}
library(epivizrChart)
library(antiProfilesData)
library(SummarizedExperiment)
```


```{r}
data(tcga_colon_blocks)
data(tcga_colon_curves)
data(tcga_colon_expression)
data(apColonData)
```


Create an epiviz enivornment
```{r}
epivizEnv <- EpivizEnvironment(chr="chr11", start=99800000, end=103383180)
```

Genes Track Demo
```{r}
library(Homo.sapiens)

genes_track <- epivizChart(Homo.sapiens, epiviz_env=epivizEnv)

genes_track
```


Blocks Track Demo
```{r eval=FALSE}
blocks_track <- EpivizChart(tcga_colon_blocks, datasource_name="450kMeth", epiviz_env=epivizEnv)

plot(blocks_track)
```


Means Track Demo
```{r}
means_track <- EpivizChart(tcga_colon_curves, datasource_name="450kMeth", type="bp", columns=c("cancerMean","normalMean"), epiviz_env=epivizEnv)

plot(means_track)
```

Scatter Plot Demo
```{r warnings=FALSE, messages=FALSE}
keep <- pData(apColonData)$SubType!="adenoma"
apColonData <- apColonData[,keep]
status <- pData(apColonData)$Status
Indexes <- split(seq(along=status),status)

exprMat <- exprs(apColonData)
mns <- sapply(Indexes, function(ind) rowMeans(exprMat[,ind]))
mat <- cbind(colonM=mns[,"1"]-mns[,"0"], colonA=0.5*(mns[,"1"]+mns[,"0"]))

pd <- data.frame(stat=c("M","A"))
rownames(pd) <- colnames(mat)

maEset <- ExpressionSet(
  assayData=mat,
  phenoData=AnnotatedDataFrame(pd),
  featureData=featureData(apColonData),
  annotation=annotation(apColonData)
)
```

```{r}
eset_chart <- EpivizChart(maEset, datasource_name="MAPlot", columns=c("colonA","colonM"), epiviz_env=epivizEnv)

plot(eset_chart)
```

SummarizedExperiment

```{r eval=TRUE}
ref_sample <- 2 ^ rowMeans(log2(assay(tcga_colon_expression) + 1))
scaled <- (assay(tcga_colon_expression) + 1) / ref_sample
scaleFactor <- Biobase::rowMedians(t(scaled))
assay_normalized <- sweep(assay(tcga_colon_expression), 2, scaleFactor, "/")
assay(tcga_colon_expression) <- assay_normalized

status <- colData(tcga_colon_expression)$sample_type
index <- split(seq(along = status), status)
logCounts <- log2(assay(tcga_colon_expression) + 1)
means <- sapply(index, function(ind) rowMeans(logCounts[, ind]))
mat <- cbind(cancer = means[, "Primary Tumor"], normal = means[, "Solid Tissue Normal"])

sumexp <- SummarizedExperiment(mat, rowRanges=rowRanges(tcga_colon_expression))

se_chart <- epivizChart(sumexp, datasource_name="Mean by Sample Type", columns=c("normal", "cancer"), epiviz_env=epivizEnv)

plot(se_chart)
```

Show epiviz enivornment
```{r}
plot(epivizEnv)
```

