---
title: "Knitting Epiviz Charts with epivizrChart"
author: "Brian Gottfried"
output:
   BiocStyle::html_document:
    includes:
      in_header: epiviz-imports.html
runtime: shiny
---

```{r setup, eval=TRUE, include=FALSE}
library(epivizrChart)
library(antiProfilesData)
```


```{r}
data(tcga_colon_blocks)
data(tcga_colon_curves)
data(apColonData)
```


Blocks Track Demo
```{r}
blocks_track <- epivizPlot(tcga_colon_blocks, datasource_name="450kMeth")

blocks_track
```


Means Track Demo
```{r}
means_track <- epivizPlot(tcga_colon_curves, datasource_name="450kMeth", type="bp", columns=c("cancerMean","normalMean"))

means_track
```

Scatter Plot Demo
```{r warnings=FALSE, messages=FALSE}
keep <- pData(apColonData)$SubType!="adenoma"
apColonData <- apColonData[,keep]
status <- pData(apColonData)$Status
Indexes <- split(seq(along=status),status)

exprMat <- exprs(apColonData)
mns <- sapply(Indexes, function(ind) rowMeans(exprMat[,ind]))
mat <- cbind(colonM=mns[,"1"]-mns[,"0"], colonA=0.5*(mns[,"1"]+mns[,"0"]))

pd <- data.frame(stat=c("M","A"))
rownames(pd) <- colnames(mat)

maEset <- ExpressionSet(
  assayData=mat,
  phenoData=AnnotatedDataFrame(pd),
  featureData=featureData(apColonData),
  annotation=annotation(apColonData)
)
```
```{r include=FALSE}
eset_chart <- epivizPlot(maEset, datasource_name="MAPlot", columns=c("colonA","colonM"))
```

```{r eval=FALSE}
eset_chart <- epivizPlot(maEset, datasource_name="MAPlot", columns=c("colonA","colonM"))
```
```{r}
eset_chart
```

Create an epiviz enivornment
```{r}
epivizEnv <- epivizEnvironment(chr="chr11", start=99800000, end=103383180)

charts <- list(blocks_track, means_track, eset_chart)
for (chart in charts) {
  epivizEnv$add(chart)
}

```

Show the epiviz environment
```{r}
epivizEnv
```



```{r}
env <- epivizEnvironment(
  attributes=list(chr, start, end),
  children=list(
    blocks_chart,
    epivizNavigation(
      attributes=list(chr,start,end),
      children=list(
        means_track,
        eset_chart
      )
    )
  )
)

epivizEnv <- epivizEnvironment(chr="chr11", start=99800000, end=103383180)

blocks_track <- epivizPlot(tcga_colon_blocks, datasource_name="450kMeth", environment=epivizEnv)
# If environment field is not NULL, use environment's data manager AND append chart to epivizEnv
```
